version: "3"

services:

  config:
    image: virtual-gpu
    stdin_open: true
    tty: true
#    volumes:
#      - ~/data/:/var/www/
# you can add your data set models/folders in volume section to retrieve them in the gpu
